### Recuperar todas las fields
GET http://localhost:8000/api/fields

### Recuperar field por id
GET http://localhost:8000/api/fields/1

### Recuperar todas las fields por filtro
GET http://localhost:8000/api/fields?deporte=futbol

### Crear una chanca nueva
POST http://localhost:8000/api/fields
Content-Type: application/json

{
    "nombre": "El monumental",
    "descripcion": "El monumental",
    "precio": 12.30,
    "deporte": "futbol",
    "ciudad": "buenos aires"
}

### Actualizar o modificar una cancha
PATCH http://localhost:8000/api/fields/10
Content-Type: application/json

{
    "deporte": "tenis"
}

### Eliminar una cancha
DELETE http://localhost:8000/api/fields/9